# Generated by Django 5.2.13 on 2026-07-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_location_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='state_division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
