# Generated by Django 5.2.13 on 2026-08-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_locationphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
